"""Pydantic models with thorough validation for the security-hardened service."""

from pydantic import BaseModel, Field, field_validator
import re


class GenerateRequest(BaseModel):
    """
    Request body for the /generate endpoint.

    Instructor note:
      Pydantic validation is the first line of defense. It rejects malformed
      input before it reaches the model. The validators below demonstrate
      defense-in-depth: length limits, content filtering, and type constraints
      all work together to reduce the attack surface.
    """
    prompt: str = Field(
        ...,
        min_length=1,
        max_length=1024,
        description="The input text prompt for generation.",
        examples=["Explain the benefits of containerization"],
    )
    max_tokens: int = Field(
        default=50,
        ge=1,
        le=256,  # Tighter limit for security demo
        description="Maximum number of new tokens to generate.",
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Sampling temperature.",
    )

    @field_validator("prompt")
    @classmethod
    def prompt_must_not_be_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Prompt must contain non-whitespace characters.")
        return v

    @field_validator("prompt")
    @classmethod
    def prompt_must_not_contain_injection_patterns(cls, v: str) -> str:
        """
        Basic injection pattern check.

        Instructor note:
          This is a simplified demonstration. Production systems should use
          dedicated content moderation models or APIs for robust detection.
        """
        # Check for common prompt injection markers
        suspicious_patterns = [
            r"ignore\s+(all\s+)?previous\s+instructions",
            r"<\s*script",
            r"system\s*:\s*",
        ]
        lower_v = v.lower()
        for pattern in suspicious_patterns:
            if re.search(pattern, lower_v):
                raise ValueError(
                    "Input contains potentially unsafe patterns. "
                    "Please rephrase your prompt."
                )
        return v


class GenerateResponse(BaseModel):
    prompt: str
    generated_text: str
    tokens_generated: int
    model_name: str
    fallback_used: bool = Field(
        default=False,
        description="Whether the response was generated by the fallback model.",
    )


class HealthResponse(BaseModel):
    status: str
    model_loaded: bool
    model_name: str


class ErrorResponse(BaseModel):
    """Structured error response for API consumers."""
    error: str = Field(description="Error type identifier.")
    detail: str = Field(description="Human-readable error description.")
    request_id: str | None = Field(default=None, description="Request ID for tracing.")
